#ifndef CAN_NETSIM_H
#define CAN_NETSIM_H

#include <stdlib.h>
#include <stdio.h>

#include "../ihb.h"

/*
 * ihb_skin_module_info() - print can submodule info
 */
void ihb_skin_module_info(void);

/*
 * skin_node_handler() - handler of skin user-space tools
 *
 * > skin fail <node> - set as expired the node
 *
 * It requires the Riot-os shell.
 */
int skin_node_handler(int argc, char **argv);

/*
 * ihb_init_netsimulator() - This thread simulate a network of Skin modules large
 *                           SK_N_S. Each module contains SK_T_S tactiles sensors.
 *                           The payload is generated by random function.
 *
 * @ihb_ctx: ihb contex
 */
int ihb_init_netsimulator(struct ihb_ctx *ihb_ctx);

#endif
