MODULE := ihbcan

RIOT_INCLUDE   := $(RIOTBASE)/sys/include
RIOT_CORE_INC  := $(RIOTBASE)/core/include

FEATURES_REQUIRED = periph_cpuid
FEATURES_REQUIRED += periph_can

include $(RIOTBASE)/Makefile.base
